---
# tasks file for cloning terraform modules
- name: Clone a github repository {{ gcp_vm_tf_source|basename }}
  ansible.builtin.git:
    repo: '{{ gcp_vm_tf_source }}'
    dest: '{{ gcp_vm_tf_module_path }}'
    clone: yes
    update: yes
    version: main

