---
- name: Create GCP Firewall Rule
  google.cloud.gcp_compute_firewall:
    state: '{{ fastchat_state }}'
    project: '{{ project_id }}'
    name: 'intel-fastchat-firewall-{{ random_id }}'
    network: '{{network_name}}'
    description: "Allows access to FastChat Webserver."
    allowed:
      - ip_protocol: tcp
        ports: '{{ ports }}'
    source_ranges: "{{ source_ranges }}"
    target_tags:
      - "fschat-{{ random_id }}"
    auth_kind: serviceaccount
    service_account_file: "/tmp/fluid-tuner-405104-56caae5712d3.json"
  register: gcp_output

- debug:
    var: gcp_output
