- name: Read terraform output
  command: chdir='{{ gcp_vm_tf_module_path }}' terraform output -json
  register: gcp_vm_output_tf_output

- debug:
    var: gcp_vm_output_tf_output

- set_fact:
    gcp_vm_output_tf_output: "{{ gcp_vm_output_tf_output.stdout }}"

- debug:
    var: gcp_vm_output_tf_output

- block:
    - name: "Checking Terraform resource"
      debug:
        msg: "Terraform cannot delete the resource because it is not found in the state file. Manual intervention is required."
    - meta: end_play
  when: gcp_vm_state == 'absent' and gcp_vm_output_tf_output | length == 0

- set_fact:
    instance_id: "{{ gcp_vm_output_tf_output.id.value }}"
    instance_name: "{{ gcp_vm_output_tf_output.name.value }}"
  when: gcp_vm_output_tf_output | length > 0

- set_fact:
    random_id: "{{ instance_name.split('-')[-1] }}"
  when: instance_name | length > 0

- set_fact:
    vm_update: true
  when: gcp_vm_state == 'present' and instance_id | length > 0

- ansible.builtin.debug:
    msg:
    - "instance_id: {{ instance_id }}"
    - "random_id: {{ random_id }}"
   
