---
- set_fact:
    gcp_rhel_vm_instance : '{{ gcp_vm_output.outputs }}'
  when: gcp_vm_output.outputs | length > 0

- name: Validating gcp_rhel_vm_instance output
  fail:
    msg: "gcp_rhel_vm_instance instance got an error"
  when: gcp_vm_output.outputs | length == 0

- name: Displaying rhel vm output
  ansible.builtin.debug:
    msg:
    - "name: {{ gcp_rhel_vm_instance.name.value }}"
    - "instance_id: {{ gcp_rhel_vm_instance.instance_id.value }}"
    - "cpu_platform: {{ gcp_rhel_vm_instance.cpu_platform.value }}"
    - "boot_disk_family: {{ gcp_rhel_vm_instance.boot_disk_size.value }}"
    - "machine_type: {{ gcp_rhel_vm_instance.machine_type.value }}"

