- name: Read terraform output
  command: chdir='{{ gcp_vm_tf_module_path }}' terraform output -json
  register: fastchat_output_tf_output

- debug:
    var: fastchat_output_tf_output

- set_fact:
    fastchat_output_tf_output: "{{ fastchat_output_tf_output.stdout }}"

- debug:
    var: fastchat_output_tf_output

- block:
    - name: "Checking Terraform resource"
      debug:
        msg: "Terraform cannot delete the resource because it is not found in the state file. Manual intervention is required."
    - meta: end_play
  when: fastchat_state == 'absent' and fastchat_output_tf_output | length == 0

- set_fact:
    instance_id: "{{ fastchat_output_tf_output.id.value }}"
    instance_name: "{{ fastchat_output_tf_output.name.value }}"
  when: fastchat_output_tf_output | length > 0

- set_fact:
    random_id: "{{ instance_name.split('-')[-1] }}"
  when: instance_name | length > 0

- set_fact:
    vm_update: true
  when: fastchat_state == 'present' and instance_id | length > 0

- ansible.builtin.debug:
    msg:
    - "instance_id: {{ instance_id }}"
    - "random_id: {{ random_id }}"
   
